### ISSUE TITLE
When running migrations, invalid argument error occured.

### ISSUE THREAD

**Issue by MuhammadSadeeq** [aschmelyun/docker-compose-laravel#101]
![image](https://user-images.githubusercontent.com/54463147/116054473-253c9f80-a695-11eb-9327-5f510b28a8d5.png)

**Comment by serwin35** [comment]
Hi, 
add file .dockerignore to folder profound-docker

File: .dockerignore
`# Laravel
src/bootstrap/cache
src/node_modules/
src/storage/framework
src/storage/logs
src/public/storage
src/vendor`

**Comment by MuhammadSadeeq** [comment]
> Hi,
> add file .dockerignore to folder profound-docker
> 
> File: .dockerignore
> 
> ```
> # Laravel
> src/bootstrap/cache
> src/node_modules/
> src/storage/framework
> src/storage/logs
> src/public/storage
> src/vendor
> ```

@serwin35 Thank you so much. saved my day 👍
