### ISSUE TITLE
 Doctrine\DBAL\Driver\PDO\Exception    could not find driver

### ISSUE THREAD

**Issue by MuhammadSadeeq** [aschmelyun/docker-compose-laravel#102]
I need to install tcg/voyager in my project. When I ran the following command,
`docker-compose run --rm composer require tcg/voyager`
it gave me this error:
![image](https://user-images.githubusercontent.com/54463147/116069780-39889880-a6a5-11eb-8342-91abbe204def.png)

**Comment by n1kio** [comment]
@MuhammadSadeeq Did you find a solution for this?
