### ISSUE TITLE
ERROR: Encountered errors while bringing up the project.

### ISSUE THREAD

**Issue by omerhabib62** [aschmelyun/docker-compose-laravel#103]
ERROR: for mysql  Cannot create container for service mysql: Conflict. The container name "/mysql" is already in use by container "168e8e192c62a7c40f2d50b3fec7ea52091304f5ba527c5c9b71717a40d5d551". You have to remove (or rename) that container to be able to reuse that name.

**Comment by aschmelyun** [comment]
If you're running another Docker project with the same service name, this could create the conflict. Additionally, you can rename the `mysql` service to something else (like `db`) to prevent this from happening.

If you're not running another Docker project, you can run `docker system prune` to remove any unused containers that could be causing this conflict!
