### ISSUE TITLE
Problem with Laravel Tenancy Mysql

### ISSUE THREAD

**Issue by wdevmaster** [aschmelyun/docker-compose-laravel#106]
Hello, how are you friends? I have a problem since I have a system that is structured with this package:

https://github.com/tenancy/tenancy

Which allows me to have different DBs for the clients since it is a service for companies, so when using the environment that docker when executing the migrations docker compose run --rm artisan migrate: refresh --seed the system creates two clients this process triggers an event within the package that automatically creates a new user for mysql and a database for that specific client; that new user instead of having the `Host 127.0.0.1` has the name of the mysql service, this is causing the user to not be able to connect to the corresponding database, as could be done to reuse the ip `127.0.0.1` with this docker environment.

.env
`DB_CONNECTION=mysql`
`DB_HOST=mysql`
`DB_PORT=3306`
`DB_DATABASE=dev_tenant`
`DB_USERNAME=root`
`DB_PASSWORD=secret`
`DB_PREFIX_TENANT="${DB_DATABASE}"`

Error terminal
`SQLSTATE[HY000] [1045] Access denied for user 'dev_tenant_ZUwr5'@'172.30.0.7' (using password: YES) (SQL: select * from information_schema.tables where table_schema = dev_tenant_ZUwr5 and table_name = migrations and table_type = 'BASE TABLE')
`

Table mysql.user
`Host: mysql`  <- here should go the ip (127.0.0.1) or localhost
`User: dev_tenant_ZUwr5`

**Comment by Albertopeinado96** [comment]
Hello, have you tried giving permissions on the mysql container to the dev_tenant_ZUwr5 user? Try giving the user the needed privileges to access the database.

# 1. Connect to docker container, open windows cmd:
docker exec -it mysql bash

# 2. Login to MySQL with root account
mysql --user=root --password=secret

# 3. Set root and user account to use MySQL native password 
ALTER USER 'root' IDENTIFIED WITH mysql_native_password BY 'secret';
ALTER USER 'dev_tenant_ZUwr5' IDENTIFIED WITH mysql_native_password BY 'secret';

# 4. Grant privileges to the docker mysql user
 GRANT ALL PRIVILEGES ON `dev_tenant`.* TO `dev_tenant_ZUwr5`@`%`

#5. Save the changes by issuing the FLUSH PRIVILEGES
FLUSH PRIVILEGES;
