### ISSUE TITLE
*** [Makefile:243: pdo.lo] Error 127

### ISSUE THREAD

**Issue by Martin-1182** [aschmelyun/docker-compose-laravel#107]
**I'm trying to install and I'm getting the following error. Can't advise me how to fix?**

>Service 'php' failed to build: The command '/bin/sh -c docker-php-ext-install pdo pdo_mysql' returned a non-zero code: 2
`make: /bin/sh: Operation not permitted
make: *** [Makefile:243: pdo.lo] Error 127
ERROR: Service 'php' failed to build: The command '/bin/sh -c docker-php-ext-install pdo pdo_mysql' returned a non-zero code: 2`

**Comment by psgganesh** [comment]
Looking at this solution on the web; https://www.gitmemory.com/issue/docker-library/php/1134/805349146,  I have changed the 
`php.dockerfile` to

```bash
FROM php:7.4-fpm-alpine3.12
```

And it works
