### ISSUE TITLE
Laravel Migration failed 

### ISSUE THREAD

**Issue by jacklove315** [aschmelyun/docker-compose-laravel#109]
**### Exception when i try run my db migrations:**

Illuminate\Database\QueryException 

SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known (SQL: select * from information_schema.tables where table_schema = homestead and table_name = migrations and table_type = 'BASE TABLE')

### **mysql service in docker-compose.yml**

 mysql:
    platform: linux/x86_64
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 4306:3306
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

**.env file in laravel app**

DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=4306
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret

**Comment by shinzoke** [comment]
DB_PORT=4306 port should be 3306 in your .env file
