### ISSUE TITLE
Using npm in a project where laravel Nova

### ISSUE THREAD

**Issue by Martin-1182** [aschmelyun/docker-compose-laravel#112]
How should I set up an npm container so that I can use npm with a project where laravel is new? I need to build custom tools in nova but when I go to the nova-components folder and release npm I don't build the right files. How could I solve this?  THX.

**Comment by aschmelyun** [comment]
@Martin-1182 An npm container is set up by default in this repo, and it doesn't matter if your Laravel application is new or legacy code. You would use it like this from your project's root where you have the docker-compose.yml file installed:

```bash
docker-compose run --rm npm install
docker-compose run --rm npm run dev
```
