### ISSUE TITLE
Can not fetch APKINDEX

### ISSUE THREAD

**Issue by ExXxO** [aschmelyun/docker-compose-laravel#113]
If i build my compose with the given command there will stuck while try fetching APKINDEX

root@APP02:~/laratest# docker-compose up -d --build site
Pulling mysql (mysql:5.7.29)...
5.7.29: Pulling from library/mysql
54fec2fa59d0: Pull complete
bcc6c6145912: Pull complete
951c3d959c9d: Pull complete
05de4d0e206e: Pull complete
319f0394ef42: Pull complete
d9185034607b: Pull complete
013a9c64dadc: Pull complete
58b7b840ebff: Pull complete
9b85c0abc43d: Pull complete
bdf022f63e85: Pull complete
35f7f707ce83: Pull complete
Digest: sha256:95b4bc7c1b111906fdb7a39cd990dd99f21c594722735d059769b80312eb57a7
Status: Downloaded newer image for mysql:5.7.29
Building php
Sending build context to Docker daemon  136.7kB
Step 1/7 : FROM php:7.4-fpm-alpine
7.4-fpm-alpine: Pulling from library/php
5843afab3874: Pull complete 
cfcf566573f3: Pull complete 
f4ff9828d954: Pull complete 
165b10189b0f: Pull complete 
7fbf46d81074: Pull complete 
ab783d928286: Pull complete 
815a8e73490f: Pull complete 
fc171a495e28: Pull complete 
0d217a6c1ef1: Pull complete 
ff975695c8bb: Pull complete 
Digest: sha256:41061531db37c76d86feb73e6b17ebedd3f425c4732cfc6e84bbf4227cc4ccf8
Status: Downloaded newer image for php:7.4-fpm-alpine
 ---> 5ae3ea657944
Step 2/7 : ADD ./php/www.conf /usr/local/etc/php-fpm.d/
 ---> a90fe8082627
Step 3/7 : RUN addgroup -g 1000 laravel && adduser -G laravel -g laravel -s /bin/sh -D laravel
 ---> Running in 5de6b5d6c036
Removing intermediate container 5de6b5d6c036
 ---> 41398928dc38
Step 4/7 : RUN mkdir -p /var/www/html
 ---> Running in b320ecbcc434
Removing intermediate container b320ecbcc434
 ---> 3fe6bf05feb7
Step 5/7 : RUN chown laravel:laravel /var/www/html
 ---> Running in 696a832fe687
Removing intermediate container 696a832fe687
 ---> 7e8a27f2b43f
Step 6/7 : WORKDIR /var/www/html
 ---> Running in cff2641a452f
Removing intermediate container cff2641a452f
 ---> 079876084dfb
Step 7/7 : RUN docker-php-ext-install pdo pdo_mysql
 ---> Running in 9aaeaf67fa04
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz

**Comment by aschmelyun** [comment]
@ExXxO Are you still having an issue with this? I haven't seen this before, and looks like it might have been a localized outage.
