### ISSUE TITLE
Artisan container can not perform composer commands

### ISSUE THREAD

**Issue by SamLoys** [aschmelyun/docker-compose-laravel#114]
Hi, 
I am using your setup for some time now and it works great.
The only thing that can be a bit confusing sometimes is that the artisan container does not have access to composer, and therefore cannot run all commands. For example installing a laravel starter pack  `php artisan breeze:install vue` . This command also installs some composer dependencies which now fail. Would it be "better" to add composer to the PHP dockerfile and create a new artisan service which is just a different entrypoint in the PHP container?

**Comment by shinzoke** [comment]
Ive added composer inside the php dockerfile and dropped the specified artisan and composer service in the docker compose file... that Made it work for my setup... 
keeping composer as a specified service with the --remove requirements flag created some errors for me...

I can share my setup if you want...
Made it compatible for https with mkcert aswell

**Comment by SamLoys** [comment]
If you dont mind sharing that would be great :)

**Comment by shinzoke** [comment]
Sure np, currently not at home, but ill drop you a repo link later on today ;)

**Comment by shinzoke** [comment]
Sorry voor de late reactie, (sorry noticed you are from enschede 😃)
Anyway, i've created a public repo with the complete setup/structure etc. 
Giving credit towards @aschmelyun for the original repo here ofc.

here the link => https://github.com/shinzoke/docker_local-development_mkcert
ps. it's my first public repo 😅

**Comment by SamLoys** [comment]
Thank you very much! This will definitely help me :) 

bedankt!
