### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by heychazza** [aschmelyun/docker-compose-laravel#116]
Hi,

Firstly, thanks for creating this! I was struggling massively for dockerising my laravel app.

When running `npm run Dev` I get:
```
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
```

Any reason why?

**Comment by devellopah** [comment]
> Hi,
> 
> Firstly, thanks for creating this! I was struggling massively for dockerising my laravel app.
> 
> When running `npm run Dev` I get:
> 
> ```
> glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
>   errno: -13,
>   code: 'EACCES',
>   syscall: 'scandir',
>   path: '/root/.npm/_logs'
> }
> ```
> 
> Any reason why?

Should be `docker-compose run --rm npm run dev`
