### ISSUE TITLE
crontab not work

### ISSUE THREAD

**Issue by mohsenmojadam2019** [aschmelyun/docker-compose-laravel#118]
hello
According to your clip, I left the crontab YouTube, but it gives the following error

PS C: \ Users \ mohsen \ Desktop \ docker-compose-laravel-main> docker-compose up cron
cron is up-to-date
Attaching to cron
cron | / bin / ash: redir error

**Comment by aschmelyun** [comment]
@mohsenmojadam2019 If you're still having this issue, can you show what you have under the `cron` heading in your docker-compose.yml file?
