### ISSUE TITLE
How can I run shell commands inside the container and avoid file permission problems?

### ISSUE THREAD

**Issue by beeyev** [aschmelyun/docker-compose-laravel#119]
I would like to use a shell (bash) inside the docker container and be able to run commands such as artisan migrations without any further permission problems when created files are owned by root. 
Is it possible?

I know about `docker-compose run --rm --service-ports ` but it is not convenient. 

ps I use this command to enter the shell.
`docker-compose  exec php bash`

**Comment by aschmelyun** [comment]
Hi beeyev! That is possible, you can continue using `exec` like you have been doing. If you check out the latest version of the repo and the README, I've worked a lot to fix the permissions issues with file ownership.

Let me know if you have any other problems!
