### ISSUE TITLE
Can't create new Laravel project - [RuntimeException] Could not delete /var/www/html/.

### ISSUE THREAD

**Issue by kieferslaton** [aschmelyun/docker-compose-laravel#121]
Hello, 

Just got this installed on our remote server and trying to install my laravel project, but when I cd into src and run docker-compose run --rm composer create-project laravel/laravel . I get the following error:

Install of laravel/laravel failed

                                     
  [RuntimeException]                 
  Could not delete /var/www/html/.:

Any idea what could be happening here?

**Comment by aschmelyun** [comment]
Hey all! Try pulling down the latest version of this repo and running `docker-compose build --no-cache` in your project. I just did a ton of work with the permissions issues, and this hopefully should solve your problem.

There's some more info in the README as well!

**Comment by heychazza** [comment]
I'm having this same issue all of a sudden.. :/

**Comment by santanubiswascispl** [comment]
Anyone found any solution to this? Tried everything mentioned in the README but issue remains same

**Comment by aschmelyun** [comment]
Try going through #49 for any issues related to permissions issues, or check out the section in the README!
