### ISSUE TITLE
File permission issues on Ubuntu

### ISSUE THREAD

**Issue by joseph-d** [aschmelyun/docker-compose-laravel#126]
If I try and perform any sort of artisan task like `docker-compose run --rm artisan make:test MyTest` then I find that the `MyTest.php` file is getting created with `root:root` permissions in Ubuntu. 

I thought that this part of the artisan service would prevent this, as I'm definitely running under the user with the uid of 1000

```
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
 ```

However, I have found that the only way to run the artisan command and have the resulting files generated using uid 1000 is to have this in the artisan service:

```
      user: ${UID:-1000}:${UID:-1000}
 ```

..or, without using variables at all, simply:

```
      user: 1000:1000
 ```

So the question is, is it really necessary to be passing these under `args` as well or would it be better just to delete that block from each of the services and replace it with `user` instead?

**Comment by heychazza** [comment]
I'm also getting a "The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied" by default after installing, even with what you listed.

**Comment by joseph-d** [comment]
I think that using `chmod` is only going to provide a temporary fix. As soon as the service running in the docker container writes a new log file, it's going to be `root:root` again. So putting the `chmod` command in the dockerfile isn't going to help. The service needs to be running under user 1000 to begin with.

**Comment by decodedmrq** [comment]
Set user `laravel` to running image in `dockerfiles/php.dockerfile`


```shell
# Set user to running image
USER laravel

EXPOSE 9000 <= (Optinal)
CMD ["php-fpm", "-y", "/usr/local/etc/php-fpm.conf", "-R"]
```
