### ISSUE TITLE
Page Expired due to inactivity

### ISSUE THREAD

**Issue by techguydev** [aschmelyun/docker-compose-laravel#135]
@aschmelyun  First of all, thanks a lot for sharing this great tool.

I have followed the instructions and I have been able to see the website in the browser, although after I login in the Laravel App I am getting a blank page with the text " Page Expired due to inactivity"

The project works great in another environment such as Laravel Valet.

I am using :

Php 7.2
Mysql:latest

The project is running with Laravel 5.7 Version

I have tried the instructions regarding permissions in the docs but the problem persists.

**Comment by aschmelyun** [comment]
This issue doesn't sound like it's a problem with the Docker setup, page inactivity has to do with a csrf token or session tokens missing or misconfigured in your app. Maybe try checking your .env file's configuration if you're using a custom domain with the Docker setup -vs- valet.
