### ISSUE TITLE
McDonalds

### ISSUE THREAD

**Issue by willosbourne** [aschmelyun/docker-compose-laravel#140]
yea can i get a uuhh large fry and two mcdoubles

**Comment by willosbourne** [comment]
I'm sorry for the spam, I had to.
https://twitter.com/aschmelyun/status/1506960015063625733
love the idea :)

**Comment by RGBCube** [comment]
mcmodules*

**Comment by sw-yx** [comment]
honestly surprised this repo hasn't been flooded by spam since it is clearly visible in the video

**Comment by haydenk** [comment]
Dude, this is a Wendy's restaurant.
