### ISSUE TITLE
Multiple site with phpmyadmin 

### ISSUE THREAD

**Issue by atifsaeed14** [aschmelyun/docker-compose-laravel#18]
how we can host multiple site inside docker

**Comment by atifsaeed14** [comment]
@aschmelyun nice tutorial but I want to run one mysql / phpmyadmin then use multiple php projects (Wordpress / Laravel / php) same we do mamp / lamp.

**Comment by AdrienPoupa** [comment]
You should have one project per docker-compose

**Comment by aschmelyun** [comment]
Agree with @AdrienPoupa, docker-compose.yml should be specific to a single project so I won't be including anything in this repo to support multiple sites.

However, with what @atifsaeed14 is asking for, you can run a single Docker container instance of mysql, phpmyadmin, etc, and as long as it's attached to the same network as your docker-compose.yml orchestrations (and there's no port conflicts), your other applications can all access that central container running.

I hope that helps!

For more info, check out these links:

- https://docs.docker.com/engine/reference/commandline/run/ 
- https://docs.docker.com/network/
