### ISSUE TITLE
Run Artisan commands

### ISSUE THREAD

**Issue by Tarhex** [aschmelyun/docker-compose-laravel#186]
How do I run artisan commands like:

`php artisan ui vue`

Thanks

**Comment by GandalfGrey** [comment]
In the readme file under '[Usage](https://github.com/aschmelyun/docker-compose-laravel#usage)' you have examples how to use composer, npm and artisan commands.
`docker-compose run --rm composer update`
`docker-compose run --rm npm run dev`
`docker-compose run --rm artisan migrate`

So in your case it should be `docker-compose run --rm artisan ui vue`

**Comment by Tarhex** [comment]
It worked. Thanks, I appreciate.
