### ISSUE TITLE
Laravel Horizon

### ISSUE THREAD

**Issue by spintokha** [aschmelyun/docker-compose-laravel#191]
Hi,

someone have installed Laravel Horizon?
I've installed, but sometimes getting many issues like:
![image](https://user-images.githubusercontent.com/10213459/168319768-e169ad1a-3fe9-43ba-8794-168ceeed3b5c.png)
![image](https://user-images.githubusercontent.com/10213459/168321077-11c505d6-c59b-4ddf-a2fe-32dd922e2837.png)

Can somebody help me with this?
Thank you.

**Comment by aschmelyun** [comment]
Please add more details if you're still having this issue. I can't really do much debugging with what's been presented, sorry!
