### ISSUE TITLE
Redis Installation 

### ISSUE THREAD

**Issue by kingrootid** [aschmelyun/docker-compose-laravel#193]
=> ERROR [laravel-whatsapp-server_php 11/11] RUN mkdir -p /usr/src/php/ext/redis     && curl -L https://github.com/phpredis/phpredis/archive/5.3.4.tar.gz | tar xvz -C /usr/src/php/ext/redis --strip 1     && echo 'redis' >> /usr/src/php-available-exts     && docker-php-ext-install redis                                           6.3s 
------
 > [laravel-whatsapp-server_php 11/11] RUN mkdir -p /usr/src/php/ext/redis     && curl -L https://github.com/phpredis/phpredis/archive/5.3.4.tar.gz | tar xvz -C /usr/src/php/ext/redis --strip 1     && echo 'redis' >> /usr/src/php-available-exts     && docker-php-ext-install redis:
#0 0.581   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#0 0.581                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0curl: (6) Could not resolve host: codeload.github.com
#0 5.791 gzip: invalid magic
#0 5.791 tar: Child returned status 1
#0 5.791 tar: Error is not recoverable: exiting now
------
failed to solve: executor failed running [/bin/sh -c mkdir -p /usr/src/php/ext/redis     && curl -L https://github.com/phpredis/phpredis/archive/5.3.4.tar.gz | tar xvz -C /usr/src/php/ext/redis --strip 1     && echo 'redis' >> /usr/src/php-available-exts     && docker-php-ext-install redis]: exit code: 2

**Comment by aschmelyun** [comment]
Looks like there's an issue reaching the `codeload.github.com` domain from your machine. Unfortunately this issue isn't relevant to Docker or this repo.
