### ISSUE TITLE
[Question] Deploy on Heroku

### ISSUE THREAD

**Issue by douglas-pereira-startse** [aschmelyun/docker-compose-laravel#196]
Is it possible to deploy this container with a laravel application to heroku? 

Would anyone know how I can do this?

**Comment by aschmelyun** [comment]
This is a pretty good article on deploying a Dockerized Laravel application to Heroku: https://dev.to/abbasogaji/how-to-dockerize-your-laravel-app-for-heroku-container-registery-23oa

Hope it helps!
