### ISSUE TITLE
Not working on Ubuntu v22.04 + Docker Desktop v4.10.1 due to permission issues

### ISSUE THREAD

**Issue by raveren** [aschmelyun/docker-compose-laravel#197]
I'm coming from the search for solution to this problem:

https://stackoverflow.com/questions/73043836/files-owner-inside-docker-is-root-service-user-is-not-root-trouble-with-permis

I resorted to trying something known-to-work and it doesn't! I did my own tests and then everything step by step as suggested by the readmes of this project and:

![image](https://user-images.githubusercontent.com/364220/179941745-b12b4755-46f0-4307-a3c8-5150b7759bd5.png)

Same in the `src` directory. All files inside the container are owned by `root`.

Has anyone encountered this?

**Comment by aschmelyun** [comment]
Try going through the thread in #49 and see if any of those solutions work for you!
