### ISSUE TITLE
Docker compose up failed when building artisan

### ISSUE THREAD

**Issue by diegoulloao** [aschmelyun/docker-compose-laravel#20]
Docker compose up failed when building artisan

`docker-compose up -d --build`

```
ERROR: for artisan  Cannot start service artisan: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/var/www/html/artisan\": permission denied": unknown
```

App is right at /src folder.

**Comment by Bert210** [comment]
You need to add php to the entrypoint array for artisan service.
As noted in https://github.com/aschmelyun/docker-compose-laravel/issues/8

**Comment by diegoulloao** [comment]
Thanks! that works.
