### ISSUE TITLE
Vite HMR

### ISSUE THREAD

**Issue by killemalljustice** [aschmelyun/docker-compose-laravel#201]
Hi, anyone knows what changes need to be made for vite HMR works as intended in a fresh Laravel Breeze Vue application ?

**Comment by aschmelyun** [comment]
Hey @killemalljustice, check out the latest update. I've published some changes to this repo that lets you use Vite and includes support for hot-module reloading. There's a whole section in the README about it!

**Comment by cornernote** [comment]
see #218
