### ISSUE TITLE
Not relevant with Laravel 9, need an update.

### ISSUE THREAD

**Issue by Yevhenii-Web-dev** [aschmelyun/docker-compose-laravel#202]
Node ancient haw error with "Vite".

"Using BrowserSync with Laravel Mix" is not relevant because laravel 9 node use webpack it is changed on vite. config.

How can I fix "Using BrowserSync with Laravel Mix" for vite. config ?

**Comment by aschmelyun** [comment]
Check out the latest update. I've published some changes to this repo that lets you use Vite and includes support for hot-module reloading. There's a whole section in the README about it!
