### ISSUE TITLE
To run artisan on windows 10, version 3.9 docker, I am getting the below error 

### ISSUE THREAD

**Issue by vvsrrSunny** [aschmelyun/docker-compose-laravel#203]
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/var/www/html/artisan": stat /var/www/html/artisan: no such file or directory: unknown

**Comment by aschmelyun** [comment]
You have to install Laravel into the `/src` directory. Either by copying an existing project into it, or by running the following commands from your project root:

```
rm src/README.md
docker-compose run --rm composer create-project laravel/laravel .
```
