### ISSUE TITLE
Linux permisson issue

### ISSUE THREAD

**Issue by chiragparekh** [aschmelyun/docker-compose-laravel#205]
Hi,

I am using linux machine, I have setup the files as the instruction in the readme. 

Now when I run `docker-compose run --rm artisan make:controller TestController` command then I am not able to edit that file from the local file system.

I have tried the following but it didn't fix the issue:
![image](https://user-images.githubusercontent.com/1888712/201482956-51c13242-af85-4a89-95d1-6ac2b2ed77b5.png)

Can you advice me on this?

**Comment by aschmelyun** [comment]
Check out some of what's been talked about in #49, but basically you'll need to ensure that the user created during the Docker image build has the **same uid and gid** as the user that owns the files in your local environment. You can try `chown`'ing the src folder after spinning up the containers and seeing if that helps as well!
