### ISSUE TITLE
View node js version

### ISSUE THREAD

**Issue by eliasbermarq** [aschmelyun/docker-compose-laravel#209]
How can I see the version of node js running through a command on which container?

Thanks

**Comment by ilhamdev0** [comment]
make sure nodejs container is running, then get the name or id of nodejs container with following command:

`docker ps`

then use this command to run command inside container:

`docker exec -it <name or id> node -v` or `docker exec -t <name or id> node -v`

example: `docker exec -it 89ycxxxxa node -v`

**Comment by aschmelyun** [comment]
Even better is that you can use the `docker-compose` alias and pass in the service name, so you don't have to get the container id!

```
docker-compose exec npm node -v
```
