### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by DlouhyDavid** [aschmelyun/docker-compose-laravel#215]
Does the current docker-compose also support Laravel 10 with Vue and Vite? What specific steps are needed?

When I tried to follow the readme, I got the following errors in the console:
`GET http://0.0.0.0:5173/@vite/client net::ERR_ADDRESS_INVALID`
`GET http://0.0.0.0:5173/resources/js/app.js net::ERR_ADDRESS_INVALID`

**Comment by cornernote** [comment]
@DlouhyDavid , I think it's the same as #218
