### ISSUE TITLE
Support for Laravel Mix Hot Module Replacement

### ISSUE THREAD

**Issue by veakabori** [aschmelyun/docker-compose-laravel#23]
Have you considered adding a container that could run the "npm run hot" command?

**Comment by aschmelyun** [comment]
This is covered with the latest update. You can now use the `npm run dev` script which (if you're using Vite) sets up your project to use hot-module reloading. See [these details](https://github.com/aschmelyun/docker-compose-laravel#compiling-assets) for more info!
