### ISSUE TITLE
 mysql reject connection when i add volume to mysql in docker-compose.yml

### ISSUE THREAD

**Issue by adrian250997** [aschmelyun/docker-compose-laravel#28]
Hi, I have a problem, I added volumes to mysql so that my data would not disappear by running the command "docker-compose down", I added: 
```
volumes: 
-./mysql:/var/lib/mysql 
```
to the mysql configuration in the file docker-compose.yml along with the mysql directory at the root of the project, it doesn't give me errors when giving "docker-compose up" but when I try to do anything to the database, it rejects the connection with error 2002, even if I try to enter with heidi to the host and port rejects the connection, what can it be?

**Comment by bsholdice** [comment]
anything informative in the output of `docker logs -f mysql` ?
Is the volume mounted to the container? (check `docker inspect mysql`)

**Comment by adrian250997** [comment]
@bsholdice  este es el error que me sale : 
![image](https://user-images.githubusercontent.com/33580067/80048205-21e86400-84d5-11ea-8d7b-88752c503bc8.png)

**Comment by bsholdice** [comment]
that is a failure to resolve the mysql host. doublecheck your .env entry for DB_HOST. Check the docker-compose.yaml file and confirm that nginx, mysql, php and  composer services all are attached to the  laravel network. Troubleshoot it by opening a shell on your php service (something like docker-compose exec mysql sh) and confirm it can resolve your mysql host by hostname. you may need to add necessary troubleshooting packages (ping, dig etc)

**Comment by zFly** [comment]
Hey I ran into the same problem.
I simply forgot to update the `.env` file in my laravel project to

```
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret
```

**Comment by ASRauliki** [comment]
I have the same error about not connecting to the mysql when doing artisan migrate.
Now when I try to connect with SQL Pro I have error:
MySQL said: Access denied for user 'homestead'@'172.18.0.1' (using password: YES)
Why 178.18.0.1? It was 127.0.0.1 , and that's the ip I gave.

docker inspect mysql give this:
"IPAddress": "172.18.0.3",

logs:
2020-05-13T16:20:42.290828Z 2 [Note] Access denied for user 'homestead'@'172.18.0.1' (using password: YES)
2020-05-13T16:21:08.413553Z 3 [Note] Access denied for user 'homestead'@'172.18.0.1' (using password: YES)
2020-05-13T16:26:07.995611Z 4 [Note] Access denied for user 'homestead'@'172.18.0.1' (using password: YES)

**Comment by ASRauliki** [comment]
As a follow up, I connected using 127.0.0.1 , login and pass in TablePlus, same data in .env in Laravel install doesn't work -> artisan can't migrate data
Could anyone who has mysql working put data from docker-compose.yml and .env (without pass of course :D)

**Comment by zFly** [comment]
I think the best thing for you would be to watch this [tutorial](https://www.youtube.com/watch?v=5N6gTVCG_rw) by the repo owner himself. 

In this video he goes over the setup step by step and around the 12min mark he talks about `php artisan migrate`

**Comment by ASRauliki** [comment]
For others information - you need to put mysql or pgsql as your host, not localhost or 127.0.0.1 even though it works with 127.0.0.1 in SQL Pro or TablePlus

**Comment by iamsarthakjoshi** [comment]
(Please skip step 1, 2 and 3 **if** the container/service name i.e. "mysql" works fine for DB_HOST.)

1) Fire this command to check the IP addresses of each services in the network:
`docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)`

2) You will see output something like this:
`/composer - 
/nginx - 172.18.0.6
/artisan - 
/php - 172.18.0.2
/npm - 
/mysql - 172.18.0.3`

3) Grab the IP address of mysql from Step #2 and update in DB_HOST's value in .env file.

(Please skip step 1, 2 and 3 if the container/service name i.e. "mysql" works fine for DB_HOST.

4) Fire config clear 
`docker-compose run --rm artisan config:clear`

5) Fire cache clear
`docker-compose run --rm artisan cache:clear`

6) Fire migrate refresh
`docker-compose run --rm artisan migrate:refresh`

**Comment by adrian250997** [comment]
I solved it by adding my volume to the end of my docker-compose.yml file
here i use my dbdata volume:
![image](https://user-images.githubusercontent.com/33580067/83958610-6d629180-a839-11ea-8820-978c2bf258f6.png)
and here I declare it at the end of my docker-compose.yml
![image](https://user-images.githubusercontent.com/33580067/83958600-41471080-a839-11ea-991b-4c1e6e4bdc9d.png)


I want to suppose that I was trying to use a volume that was not declared (I thought it would add the volume in automatic if it was not declared, but in my case it did not work like this)

**Comment by aschmelyun** [comment]
Looks like this issue has been resolved a few different ways and there hasn't been any activity in a while. If anyone has any updates for this, please feel free to open a new ticket and reference this one!
