### ISSUE TITLE
localhost is currently unable to handle this request.

### ISSUE THREAD

**Issue by devellopah** [aschmelyun/docker-compose-laravel#3]
I got error in browser on docker up

> This page isn’t working
localhost is currently unable to handle this request.
HTTP ERROR 500

I am on linux mint 19, docker and docker-compose are both of latest version.
Please, help to figure this out.

**Comment by aschmelyun** [comment]
Do you have an .env file in your application src directory? Was everything copied over to the `src` directory before running `docker-compose up -d`? 

Do you have any output if you run `docker-compose logs nginx` or `docker-compose logs php`?
