### ISSUE TITLE
Add support for Memcached and Redis

### ISSUE THREAD

**Issue by faizananwerali** [aschmelyun/docker-compose-laravel#32]
Please add support for Memcached and Redis with their extensions.

**Comment by aschmelyun** [comment]
Hi @faizananwerali, this is on my list to be added to this repo with accompanying video tutorials. Keep an eye out here and on my YouTube channel in the coming months for an update.

**Comment by aschmelyun** [comment]
Redis support has been added and available to the Laravel application using this setup. If you'd like to add Memcached, check out their Docker image: https://hub.docker.com/_/memcached
