### ISSUE TITLE
Can't run docker-compose run --rm npm run dev

### ISSUE THREAD

**Issue by natjesada** [aschmelyun/docker-compose-laravel#33]
error
sh: 1: cross-env: Permission denied

before I has run docker-compose run --rm npm i

**Comment by aschmelyun** [comment]
Try deleting the entire `node_modules` directory and `package-lock.json` in your `./src` folder, run the `docker-compose run --rm npm install` command, and then try using the `docker-compose run --rm npm run dev` command again.

**Comment by aschmelyun** [comment]
It looks like there hasn't been any activity in this issue in a while. If you have any updates, feel free to open it back up!
