### ISSUE TITLE
Any command within npm container errors

### ISSUE THREAD

**Issue by akw105** [aschmelyun/docker-compose-laravel#34]
Hello, 

Thank you for your excellent template, I am however struggling to run anything within the npm container. 

`$ docker-compose run --rm npm version`
{
  npm: '6.13.6',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '36.0',
  icu: '65.1',
  llhttp: '2.0.1',
  modules: '79',
  napi: '5',
  nghttp2: '1.40.0',
  node: '13.7.0',
  openssl: '1.1.1d',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.34.1',
  v8: '7.9.317.25-node.28',
  zlib: '1.2.11'
}

`$ docker-compose run --rm npm install`

npm ERR! code Z_DATA_ERROR
npm ERR! errno -3
npm ERR! zlib: incorrect data check

`$ docker-compose run --rm npm run dev`
sh: 1: cross-env: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @ development: cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-17T11_17_26_482Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: npm run development
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

`$ docker-compose run --rm npm install cross-env`
npm ERR! code EPROTO
npm ERR! syscall symlink
npm ERR! path ../which/bin/node-which
npm ERR! dest /var/www/html/node_modules/.bin/node-which
npm ERR! errno -71
npm ERR! EPROTO: protocol error, symlink '../which/bin/node-which' -> '/var/www/html/node_modules/.bin/node-which'

**Comment by oranges13** [comment]
Try deleting the node_modules folder and install from scratch?

**Comment by aschmelyun** [comment]
This seems to be an issue with the `zlib` library added in your NPM packages. Try removing it, deleting your node_modules + package-lock.json files, running `docker-compose run --rm npm install` and then `docker-compose run --rm install zlib`.

**Comment by aschmelyun** [comment]
It looks like there hasn't been any activity in this issue in a while. If you have any updates, feel free to open it back up!
