### ISSUE TITLE
Yarn support

### ISSUE THREAD

**Issue by filipbekic01** [aschmelyun/docker-compose-laravel#38]
Since most of people use Yarn for JS dependencies, you should have container for that too :)

**Comment by filipbekic01** [comment]
I searched for official repository but all i could do was:

FROM node:13.7

RUN apt-get update && \
    apt-get install yarn -y

**Comment by filipbekic01** [comment]
yarn:
    build:
      context: .
      dockerfile: Dockerfile.yarn
    container_name: yarn
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html/laravel
    entrypoint: yarn
    networks:
      - laravel

**Comment by filipbekic01** [comment]
Actually i added clean Alphine with Yarn on DockerHub. Repo is filipbekic01/yarn

**Comment by aschmelyun** [comment]
Good to know! Thanks for checking that out.
