### ISSUE TITLE
Welcome to nginx

### ISSUE THREAD

**Issue by tcagkansokmen** [aschmelyun/docker-compose-laravel#42]
Hi there,

On my local, everything seemed that ok.
But I try to connect localhost:8080, it let me "wel come to ngninx" page. not laravel.

And when I try to deploy for elasticbeanstalk, it gives error.

Whats wrong with it?

**Comment by aschmelyun** [comment]
Have you added your Laravel code to the `src` directory?

**Comment by taha-ahmadi** [comment]
I have the same problem!

**Comment by JonattanD1440** [comment]
I'm getting a 404 not found

**Comment by aschmelyun** [comment]
It looks like there hasn't been any activity in this issue in a while. If you have any updates, feel free to open it back up!
