### ISSUE TITLE
Cannot start service nginx

### ISSUE THREAD

**Issue by OksanaHasdaiko** [aschmelyun/docker-compose-laravel#43]
I have issue on UP. 
Does anybody have an idea how to fi this?

![Знімок екрана 2020-06-09 о 19 02 17](https://user-images.githubusercontent.com/32094527/84172621-e73a8b00-aa84-11ea-9dc3-7fac86666928.png)

**Comment by aschmelyun** [comment]
It looks like you haven't added your Laravel code to the `src` directory before spinning the containers up. Try doing that, and bringing it up again.
