### ISSUE TITLE
npm install doesn't work on my docker instance

### ISSUE THREAD

**Issue by dalarworld** [aschmelyun/docker-compose-laravel#44]
I am having issue with following commands.
docker-compose run --rm npm install
docker-compose run --rm npm run dev

For some reason it never finish installation. I tried to change npm to latest & 14.0 both failed
I am running docker on windows. Everything else works fine. Can someone help me with this so I can compile my assets in laravel application.
PS: posting issue after hours of trial & errors, removing folder etc etc.

**Comment by aschmelyun** [comment]
Can you please post the console output when you run the command above? Either copy and paste, or share a screenshot. It'll help me figure out what's going on!

**Comment by dalarworld** [comment]
When I boot up instances they work fine ..
![image](https://user-images.githubusercontent.com/16445005/84887543-82e67f80-b0b3-11ea-8987-ca8af7e064f3.png)
Half way installation they get stuck somewhere...
![image](https://user-images.githubusercontent.com/16445005/84887850-ff795e00-b0b3-11ea-8900-65bcd9401799.png)
It has been different places all the time not fix error...
I even tried command
`docker-compose run  --rm npm install --save --no-bin-link`
![image](https://user-images.githubusercontent.com/16445005/84887986-33548380-b0b4-11ea-89db-b8b106899bb1.png)

Instance stats:
![image](https://user-images.githubusercontent.com/16445005/84888036-4c5d3480-b0b4-11ea-97c9-ac0d36b48d7f.png)

I have to stop windowds docker server  & restart to get rid of this instance which is stuck at some point.

**Comment by dalarworld** [comment]
Gave it another try ... I ran command from npm bin bash
![image](https://user-images.githubusercontent.com/16445005/84941231-b4d10380-b0fe-11ea-96fc-5af9ca018206.png)

I am trying to build development environment and installing & running node is essential, please help.

**Comment by dalarworld** [comment]
I did log into bash and ran npm comman from inside several times after few errors it installed.  Wired was I din;t do anything than firing command again few time... :) 
but it worked finally..
