### ISSUE TITLE
Operation Not Permitted Nginx

### ISSUE THREAD

**Issue by Jchann24** [aschmelyun/docker-compose-laravel#51]
Hello, I'm new to docker. I can't run the nginx container because of the volume mounting. 
Here is the log. 
(Laravel is in the src folder, no ports blocking)

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration

/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/

/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh

10-listen-on-ipv6-by-default.sh: error: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)

/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh

/docker-entrypoint.sh: Configuration complete; ready for start up

2020/07/11 20:53:25 [emerg] 1#1: open() "/etc/nginx/conf.d/default.conf" failed (1: Operation not permitted) in /etc/nginx/nginx.conf:31

nginx: [emerg] open() "/etc/nginx/conf.d/default.conf" failed (1: Operation not permitted) in /etc/nginx/nginx.conf:31
```

I have tried to build the nginx container with a seperate dockerfile to COPY the ./nginx/default.conf to /etc/nginx/conf.d but I only got the default Nginx welcome page.

Thank you for your help!

**Comment by aschmelyun** [comment]
I did some research and found a similar issue someone was having here: https://github.com/nginxinc/docker-nginx/issues/416

Try changing the `docker-compose.yml` file's nginx image from `nginx:stable-alpine` to `nginx:latest` or `nginx:1.19`, bringing the container network back up again, and seeing if that fixes the issue.
