### ISSUE TITLE
create laravel app inside scr

### ISSUE THREAD

**Issue by Silver343** [aschmelyun/docker-compose-laravel#52]
Hi is there a way to create a Laravel project inside of the src folder rather than moving one to it, I have tried too by using `composer create-project --prefer-dist laravel/laravel src` but this creates it in src/sr

thanks.

**Comment by pidab** [comment]
Just run composer directly from `docker-compose-laravel`, not from `docker-compose-laravel/src`. To make this work, remove `src`.

[New instructions](https://github.com/aschmelyun/docker-compose-laravel/blob/311e3990f5ccaa99d5cd74643ee5263a3e2848a5/src/README.md) on how to install a Laravel project have been published a few hours ago. However, these do not work in my case: `[InvalidArgumentException] Project directory "/var/www/html/." is not empty.`

**Comment by pidab** [comment]
Just run composer directly from `docker-compose-laravel`, not from `docker-compose-laravel/src`. To make this work, remove `src`.

[New instructions](https://github.com/aschmelyun/docker-compose-laravel/blob/311e3990f5ccaa99d5cd74643ee5263a3e2848a5/src/README.md) on how to install a Laravel project have been published a few hours ago. However, these do not work in my case: `[InvalidArgumentException] Project directory "/var/www/html/." is not empty.`

**Comment by aschmelyun** [comment]
Did you delete the `README.md` file in the `docker-compose-laravel/src` directory like it instructs at the beginning? That's most likely what this error is from.

**Comment by pidab** [comment]
It's possible I forgot to do so. Previously I ran `composer create-project --prefer-dist laravel/laravel src` instead of `docker-compose run --rm composer create-project laravel/laravel .` and to make that work I had to delete the whole `src` directory, not just the file inside it.

Would you expect different results from using `composer` vs. `docker-compose run --rm composer`?

**Comment by Silver343** [comment]
Im going to close this as `docker-compose run --rm composer create-project laravel/laravel .` works for me.
