### ISSUE TITLE
artisan tinker

### ISSUE THREAD

**Issue by Silver343** [aschmelyun/docker-compose-laravel#53]
Hi, When using the command `docker-compose run --rm artisan tinker`  

I get the error   

`Writing to /.config/psysh is not allowed.`

` at vendor/psy/psysh/src/ConfigPaths.php:217

    213|             @\mkdir($dir, 0700, true);
    214|         }
    215| 
    216|         if (!\is_dir($dir) || !\is_writable($dir)) {
    217|             \trigger_error(\sprintf('Writing to %s is not allowed.', $dir), E_USER_NOTICE);
    218| 
    219|             return false;
    220|         }`

I have added

` user: 1000:1000` to php, composer and artisan. 

Any suggestions would be appreciated

**Comment by pidab** [comment]
This typically happens after uploading an app to a production server. In my case, Tinker works with docker-compose-laravel.

The simplest solution is to add a line to `.env` to make Tinker write somewhere else, for example
`XDG_CONFIG_HOME=/path-to-app/storage/tinker`

Alternatively, [set different permissions](https://stackoverflow.com/a/46473624).
