### ISSUE TITLE
Giving a permission denied ERROR if Laravel project is cloned from another git repo

### ISSUE THREAD

**Issue by masterj0n** [aschmelyun/docker-compose-laravel#6]
```
ERROR: for artisan  Cannot start service artisan: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/var/www/html/artisan\": permission denied": unknown
```

**Comment by talha-akhoon** [comment]
check nginx folder. I had the same issue and it turned out that the default.conf was of a folder type. 
Copy the content of the nginx folder from this repo and paste it in to your project.

**Comment by Bibi40k** [comment]
On Linux or macOS, run:
chmod +x artisan
git add artisan
git commit

On Windows, run:
git add --chmod=+x -- artisan

**Comment by tizol** [comment]
I'm seeing this error 

`$ docker-compose build && docker-compose up -d
mysql uses an image, skipping
nginx uses an image, skipping
composer uses an image, skipping
npm uses an image, skipping
Building php
Step 1/3 : FROM php:7.2-fpm-alpine
 ---> c9bda1168096
Step 2/3 : WORKDIR /var/www/html
 ---> Using cache
 ---> 5ff740f210a7
Step 3/3 : RUN docker-php-ext-install pdo pdo_mysql
 ---> Using cache
 ---> a555d29ef65d
Successfully built a555d29ef65d
Successfully tagged docker-compose-laravel_php:latest
Building artisan
Step 1/3 : FROM php:7.2-fpm-alpine
 ---> c9bda1168096
Step 2/3 : WORKDIR /var/www/html
 ---> Using cache
 ---> 5ff740f210a7
Step 3/3 : RUN docker-php-ext-install pdo pdo_mysql
 ---> Using cache
 ---> a555d29ef65d
Successfully built a555d29ef65d
Successfully tagged docker-compose-laravel_artisan:latest
Starting npm ... 
php is up-to-date
mysql is up-to-date
Starting npm      ... done
Starting composer ... done
Starting artisan  ... error

ERROR: for artisan  Cannot start service artisan: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/var/www/html/artisan\": stat /var/www/html/artisan: no such file or directory": unknown

ERROR: for artisan  Cannot start service artisan: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/var/www/html/artisan\": stat /var/www/html/artisan: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.`

**Comment by aschmelyun** [comment]
So the whole issue looks like it's stemming from the fact that it can't find the `artisan` file that normally resides at the base of Laravel projects. Can you verify that you have a file that exists under the `src` directory called artisan? If not, you can remove the whole artisan service block, or update the path to the artisan file, from the `docker-compose.yml` and re-build the container network to get this resolved.

**Comment by tizol** [comment]
@aschmelyun 
The issue was generated due to the fact that in the `src` I had `src/public/index.html`
I was following along with you video tutorial. Therefore, there was no `artisan` file. 
The error logs I mentioned above were gone once I created a laravel app which generated the `artisan` file. I think we can close this issue.

**Comment by masterj0n** [comment]
I concur with @tizol. I'm closing the issue, thanks and keep your social distances.

**Comment by redefinered** [comment]
I have the artisan file in `src` folder and I still see this error. Can anyone help me please? Thanks!
