### ISSUE TITLE
npm errors

### ISSUE THREAD

**Issue by ecsuae** [aschmelyun/docker-compose-laravel#61]
First of all i would lie to thank you for such a great work you are doing for the community, words cannot admire that.
I am facing a issue when i run command docker-compose run --rm npm run dev
can someone guide me whats wrong?
<img width="1332" alt="npm-error" src="https://user-images.githubusercontent.com/6992568/90850395-ff832c00-e38a-11ea-9533-db1c2739bbcd.png">

**Comment by ecsuae** [comment]
i checked a old issue was asking to run docker-compose run --rm npm install ,i did that and tried again still some errors showing.
<img width="1246" alt="npm-error2" src="https://user-images.githubusercontent.com/6992568/90851349-d912c000-e38d-11ea-8c04-23d52dec4f59.png">

**Comment by aschmelyun** [comment]
Try doing the following and seeing if it helps:

1. Delete both `node_modules` and `package-lock.json` in your `src` directory.
2. Run `docker-compose run --rm npm install && docker-compose run --rm npm install --save-dev cross-env && docker-compose run --rm npm run dev`

If that goes through fine, you should be able to run `docker-compose run --rm npm run dev` afterwards with no issues. Let me know!

**Comment by twistn1** [comment]
`docker-compose run --rm npm run development` worked for me
You can check for scripts in package.json file
