### ISSUE TITLE
Docker create files as root

### ISSUE THREAD

**Issue by pintokha** [aschmelyun/docker-compose-laravel#62]
If run command: docker-compose run --rm artisan make:model {modelName}
a file with root privileges is created
![image](https://user-images.githubusercontent.com/10213459/90889362-5521fd80-e3b8-11ea-833d-0becc889fb43.png)
how to fix it?

**Comment by iwasherefirst2** [comment]
You need to add `user: 1000:1000`to your artisan service. You need to add this for every service that creates files that you want to edit on your machine. This is only for people working with Linux.

**Comment by pintokha** [comment]
oh, it's easy...
thank you :)
