### ISSUE TITLE
Project directory "/var/www/html/." is not empty.

### ISSUE THREAD

**Issue by maestrom4** [aschmelyun/docker-compose-laravel#66]
![laravel](https://user-images.githubusercontent.com/5810422/92419004-4f406080-f19d-11ea-8158-a05c2bd0f225.png)

After running "sudo docker-compose run --rm composer create-project laravel/laravel ." Below is the error that I got. 
  [InvalidArgumentException]                         
  Project directory "/var/www/html/." is not empty.

**Comment by machieajones** [comment]
You need to remove the readme.md file within /src

From root:
`cd src && rm README.md`

From src:
`rm README.md`

**Comment by tkorkmazer** [comment]
If you create a Laravel project under src directory and decide to remove it later on, you need to remove everything. There is a .git file inside the directory may have couse this problem.

**Comment by maestrom4** [comment]
thank u tkorkmazer

**Comment by iljandrejevbrainbase** [comment]
Remove README.md from src

**Comment by monsteronfire** [comment]
I was not able to resolve this error by just emptying the `src` folder. But I managed to get things working by deleting the `src` folder and then creating a brand new one with the same name of `src`.

**Comment by aschmelyun** [comment]
This is most likely due to the fact that there's a `README.md` in that src directory. I have it on my list to experiment with being able to generate that directory on the fly during the composer run, instead of having to rely on it committed to the repo with a shell file.

**Comment by Weberth1233** [comment]
Use the following command:
docker-compose run composer create-project laravel/laravel project name --prefer-dist

**Comment by provydon** [comment]
delete the src folder and run `docker-compose run --rm composer create-project laravel/laravel .` again, this new run will create the files in the src folder

**Comment by rintoug** [comment]
> I was not able to resolve this error by just emptying the `src` folder. But I managed to get things working by deleting the `src` folder and then creating a brand new one with the same name of `src`.

Same worked for me.

**Comment by laurianops** [comment]
It happened to me today

Delete the files from the "/var/www/html" directory,
it needs to be empty.
