### ISSUE TITLE
How to Add Linux Image in docker-compose.yml?

### ISSUE THREAD

**Issue by nabeeleteam** [aschmelyun/docker-compose-laravel#67]
How can we add linux image at the top? 

Thanks.

**Comment by 91Abdullah** [comment]
I think php image uses linux distribution i.e. Alpine example: **FROM php:7.4.10-fpm-alpine**

**Comment by aschmelyun** [comment]
This is correct. The PHP image used is pulled down from the Docker hub, and currently using `7.4-fpm-alpine`.
