### ISSUE TITLE
 [RuntimeException]   Could not delete /var/www/html/./:

### ISSUE THREAD

**Issue by buhahemal** [aschmelyun/docker-compose-laravel#69]
![error](https://user-images.githubusercontent.com/40729639/93335542-3c382b00-f844-11ea-80ea-a4abb9ed740a.PNG)

**Comment by medioseureka** [comment]
Did you solve this?

**Comment by aschmelyun** [comment]
Is your `src` directory empty? What is the OS/Version and Docker version of the system you're trying this on?

**Comment by buhahemal** [comment]
> Did you solve this?

Yes

**Comment by acabreragnz** [comment]
I have the same issue, how did you solve it @buhahemal ?

**Comment by jeroen-fs** [comment]
Same problem here, what did you do to solve this @buhahemal? 
I use Windows 10, running  an Ubuntu 20.04 from the Microsoft store, with a docker build 20.10.8.
