### ISSUE TITLE
Very slow when i implement on Macos

### ISSUE THREAD

**Issue by x2team** [aschmelyun/docker-compose-laravel#72]
i have implement at: https://github.com/x2team/docker-nginx-mysql-php-fpm
but seem rather it is so slow on my Macos 👍 
Please help me! Request from 3->4s , tested with project laravel 8.x default

**Comment by oranges13** [comment]
A newer version of Docker on MacOS (2.4) has been causing issues for a lot of people. Disabling gRPC FUSE in the preferences and restarting docker may help as well as downgrading to 2.3.0.5 https://github.com/docker/for-mac/issues/4957

**Comment by almerleoalmazan** [comment]
@oranges13 You gave me an idea to downgrade the docker desktop version to 2.3.0.5 in Windows 10 Pro without WSL and it does solved the problem 👍 Thanks
