### ISSUE TITLE
Watch for changes in the laravel project

### ISSUE THREAD

**Issue by zk-g** [aschmelyun/docker-compose-laravel#73]
Sorry if is a dumb question.

Is there a way to watch for changes and according update the project public files?

An equivalent of `npm run watch` so to speak.

So like `docker-compose run --rm npm run watch`.

Is there a way to archive this result? Thanks

**Comment by SirPoot-** [comment]
Not as efficient, but effective. `docker-compose run --rm npm run watch-poll`

https://laravel.com/docs/8.x/mix#running-mix

**Comment by zk-g** [comment]
Thanks @SirPoot- I will try

**Comment by oranges13** [comment]
`docker-compose run --rm npm run watch` works but then hogs your terminal. If you want to daemonize it, you can do `docker-compose run -d --rm npm run watch` which will keep it running in the background until stopped :+1:

You can check the logs for issues with `docker logs <container name>`
