### ISSUE TITLE
Nginx issue 

### ISSUE THREAD

**Issue by scodepress** [aschmelyun/docker-compose-laravel#79]
I'm able to run new laravel projects using docker-compose-laravel without a problem, but am having problems getting existing projects to work. This is the output for docker-compose up -d --build, docker-compose logs nginx, and docker-compose logs php. This one of my own projects cloned from github, originally created in homestead. (Error in the browser is 500).
Thanks
Building php
Step 1/7 : FROM php:7.4-fpm-alpine
 ---> b80da81889cb
Step 2/7 : ADD ./php/www.conf /usr/local/etc/php-fpm.d/www.conf
 ---> Using cache
 ---> c4eaf018f9ab
Step 3/7 : RUN addgroup -g 1000 laravel && adduser -G laravel -g laravel -s /bin/sh -D laravel
 ---> Using cache
 ---> 7d3ac53836b6
Step 4/7 : RUN mkdir -p /var/www/html
 ---> Using cache
 ---> cafe5bbd0c2d
Step 5/7 : RUN chown laravel:laravel /var/www/html
 ---> Using cache
 ---> 99e31b788143
Step 6/7 : WORKDIR /var/www/html
 ---> Using cache
 ---> a1fdab3134dc
Step 7/7 : RUN docker-php-ext-install pdo pdo_mysql
 ---> Using cache
 ---> a43070e105d0
Successfully built a43070e105d0
Successfully tagged shelfreader_php:latest
Building site
Step 1/6 : FROM nginx:stable-alpine
 ---> ea1819c829a5
Step 2/6 : ADD ./nginx/nginx.conf /etc/nginx/nginx.conf
 ---> Using cache
 ---> c5d575ef444b
Step 3/6 : ADD ./nginx/default.conf /etc/nginx/conf.d/default.conf
 ---> Using cache
 ---> 9e0e983efe05
Step 4/6 : RUN mkdir -p /var/www/html
 ---> Using cache
 ---> d695fddd71f4
Step 5/6 : RUN addgroup -g 1000 laravel && adduser -G laravel -g laravel -s /bin/sh -D laravel
 ---> Using cache
 ---> 5a0415992547
Step 6/6 : RUN chown laravel:laravel /var/www/html
 ---> Using cache
 ---> 622a09691311
Successfully built 622a09691311
Successfully tagged shelfreader_site:latest
Building composer
Step 1/3 : FROM composer:latest
 ---> 520372566db9
Step 2/3 : RUN addgroup -g 1000 laravel && adduser -G laravel -g laravel -s /bin/sh -D laravel
 ---> Using cache
 ---> 2b5a9ee5e2f6
Step 3/3 : WORKDIR /var/www/html
 ---> Using cache
 ---> ea12499c3e84
Successfully built ea12499c3e84
Successfully tagged shelfreader_composer:latest
Building artisan
Step 1/7 : FROM php:7.4-fpm-alpine
 ---> b80da81889cb
Step 2/7 : ADD ./php/www.conf /usr/local/etc/php-fpm.d/www.conf
 ---> Using cache
 ---> c4eaf018f9ab
Step 3/7 : RUN addgroup -g 1000 laravel && adduser -G laravel -g laravel -s /bin/sh -D laravel
 ---> Using cache
 ---> 7d3ac53836b6
Step 4/7 : RUN mkdir -p /var/www/html
 ---> Using cache
 ---> cafe5bbd0c2d
Step 5/7 : RUN chown laravel:laravel /var/www/html
 ---> Using cache
 ---> 99e31b788143
Step 6/7 : WORKDIR /var/www/html
 ---> Using cache
 ---> a1fdab3134dc
Step 7/7 : RUN docker-php-ext-install pdo pdo_mysql
 ---> Using cache
 ---> a43070e105d0
Successfully built a43070e105d0
Successfully tagged shelfreader_artisan:latest
php_4 is up-to-date
Starting npm_4 ... 
mysql_4 is up-to-date
Starting npm_4      ... done
Starting composer_4 ... done
Starting artisan_4  ... done
Recreating nginx_4  ... done
(base) scott@scott-Inspiron-13-7378:~/docker_sites/shelfreader$ docker-compose logs nginx
ERROR: No such service: nginx
(base) scott@scott-Inspiron-13-7378:~/docker_sites/shelfreader$ docker-compose logs php
Attaching to php_4
php_4         | [17-Oct-2020 16:41:19] NOTICE: Failed implicitly binding to ::, retrying with 0.0.0.0
php_4         | [17-Oct-2020 16:41:19] NOTICE: Failed implicitly binding to ::, retrying with 0.0.0.0
php_4         | [17-Oct-2020 16:41:19] NOTICE: fpm is running, pid 1
php_4         | [17-Oct-2020 16:41:19] NOTICE: ready to handle connections
php_4         | 192.168.176.5 -  17/Oct/2020:16:41:29 +0000 "GET /index.php" 500
php_4         | 192.168.176.4 -  17/Oct/2020:16:50:55 +0000 "GET /index.php" 500
php_4         | 192.168.176.4 -  17/Oct/2020:16:53:45 +0000 "GET /index.php" 500
php_4         | 192.168.176.4 -  17/Oct/2020:16:54:01 +0000 "GET /index.php" 500
php_4         | 192.168.176.4 -  17/Oct/2020:16:54:20 +0000 "GET /index.php" 500
php_4         | 192.168.176.4 -  17/Oct/2020:16:55:16 +0000 "GET /index.php" 500
(base) scott@scott-Inspiron-13-7378:~/docker_sites/shelfreader$

**Comment by scodepress** [comment]
Here is output of docker logs nginx_4

/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: error: ipv6 not available
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
192.168.176.1 - - [17/Oct/2020:17:54:16 +0000] "GET / HTTP/1.1" 500 5 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" "-"
192.168.176.1 - - [17/Oct/2020:17:58:11 +0000] "GET / HTTP/1.1" 500 5 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" "-"

**Comment by aschmelyun** [comment]
@scodepress What's your `docker-compose.yml` and `nginx.dockerfile` look like, if you're still having this issue.

**Comment by aschmelyun** [comment]
Looks like this issue hasn't had any activity in a while. If you have any updates, please feel free to open this back up!
