### ISSUE TITLE
How to to modify the docker-compose.yml file to make the ubuntu to 18.04

### ISSUE THREAD

**Issue by shahidkarimi** [aschmelyun/docker-compose-laravel#82]

**Comment by oranges13** [comment]
The dockerfile is using the image `FROM php:7.4-fpm-alpine` which clearly is running on alpine. If you want to use Ubuntu 18.04 you will have to find a php 7.4 ubuntu image to pull from instead. It looks like there are official Debian repos but I couldn't find one specific to ubuntu.

* https://hub.docker.com/layers/php/library/php/7.4-fpm-buster/images/sha256-77968dff69fb3dff6d2fc052d88d66811a2c370a4be959e09bf97acda10256e7?context=explore
* https://hub.docker.com/layers/php/library/php/7.4-fpm/images/sha256-77968dff69fb3dff6d2fc052d88d66811a2c370a4be959e09bf97acda10256e7?context=explore

**Comment by yura7k** [comment]
It seems that there is no ready-made image of PHP for Ubuntu, in Dockerfile you need something like that `FROM ubuntu:latest`
Then put everything you need
`RUN apt-get install php....` and ect....

**Comment by aschmelyun** [comment]
Both of the above commenters are correct, it doesn't look like there's an official Ubuntu PHP image. However, you can use the [Debian Buster Dockerfile](https://github.com/docker-library/php/blob/24ccf968d7c975d3145f2884ec5410bb2cef936a/8.0/buster/fpm/Dockerfile) as reference to how you can go about building your own, just pulling from `ubuntu:18.04` or another version you'd like.
