### ISSUE TITLE
nginx 404

### ISSUE THREAD

**Issue by mariontan** [aschmelyun/docker-compose-laravel#83]
Hi I'm very new to using docker. Thank you very much for this project.

I followed your tutorial and followed your video[https://www.youtube.com/watch?v=5N6gTVCG_rw](url). Everything is fine until index.html the website displays. The issue starts when I create a laravel project. I can create it no problem but when I access it at localhost:8080 I get a 404 not found issue for nginx/1.18.0 Your help is highly appreciated. 

I simply downloaded the project source code and ran "docker-compose run --rm composer create-project laravel/laravel" in the src directory. I did not edit any of the .yml or Dockerfiles

**Comment by mariontan** [comment]
when I run docker-compose logs nginx, I get a "ERROR: no such service: nginx error"

on another note when I run docker-compose logs artisan I get a "Could not open input file: /var/www/html/artisan" 

I'm running my docker inside a debian 9 virtual machine on VMware

thank you very much for your help!

**Comment by menkaff** [comment]
@mariontan Check your src folder it should be empty , install Laravel like [this](https://laravel.com/docs/8.x/installation)

**Comment by mariontan** [comment]
How should the src folder look like? **src/laravel/(all the app files)** or is it **src/(all the app files)**

**Comment by menkaff** [comment]
@mariontan Sorry for late answering , it is contains laravel files
![Uploading Screenshot from 2020-11-22 13-13-49.png…]()

**Comment by menkaff** [comment]
@mariontan Sorry for late answering , it is contains laravel files
![Screenshot from 2020-11-22 13-13-49](https://user-images.githubusercontent.com/8413386/99900478-ef9a2180-2cc4-11eb-99cd-2550e6c135fb.png)

**Comment by mariontan** [comment]
Hi @menkaff I tried that but it tells me server 500 when I enter at localhost 500. Maybe there is just a step I missed. Thank you very much for this.

**Comment by menkaff** [comment]
@mariontan Maybe it's just some .env config for database or something else , add these lines in your public/index.php file to find out bugs
`error_reporting(E_ALL);`
`ini_set('display_errors', 1);`

**Comment by mariontan** [comment]
thank you very much for this @menkaff

**Comment by DJEDAINI** [comment]
@mariontan 

in nginx configuration file : default.conf

change this line : 
server_name localhost;
to this line : 
server_name _;

**Comment by DJEDAINI** [comment]
@mariontan 
or try to change the listen port on nginx configuration file : 
nginx listen to 80 port and you tried to access to port 8080 this is why you got 404 not found.

**Comment by aschmelyun** [comment]
With @DJEDAINI's latest PR to the nginx config file for a catch-all, and me updating the main `docker-compose.yml` file to expose the nginx service on port **:80** instead of :8080, this should likely resolve any issues like this in the future.
