### ISSUE TITLE
Error at the moment to run docker-compose up -d --build site 

### ISSUE THREAD

**Issue by scumbagblues** [aschmelyun/docker-compose-laravel#84]
At the moment to run this command I got this error:

ERROR: Service 'php' failed to build: The command '/bin/sh -c docker-php-ext-install pdo pdo_mysql' returned a non-zero code: 11

**Comment by aschmelyun** [comment]
Are you using the default `docker-compose.yml` from the repo, or does it have any changes or additions to it, or any of the included Dockerfiles?

What system/OS are you running on currently, and what is your version of Docker or Docker Desktop?

**Comment by aschmelyun** [comment]
This error seems to be from an issue with the version of Alpine Linux attached to the container you're building from. I'd suggest trying a different version and seeing if that helps.
