### ISSUE TITLE
  file_put_contents(./composer.lock): failed to open stream: Permission denied  

### ISSUE THREAD

**Issue by a-djedaini** [aschmelyun/docker-compose-laravel#85]
When run docker-compose run --rm composer update

**Comment by nghuyan** [comment]
I have the same error

**Comment by nghuyan** [comment]
1. 

`vi docker-compose.yml`
![image](https://user-images.githubusercontent.com/17521964/111734075-aea1ca80-88bc-11eb-9e18-ec15b79f97e6.png)

2. 

`maybe change laravel -> root `

**Comment by aschmelyun** [comment]
No new updates, so I'm closing this issue. If that changes, feel free to open this back up!
