### ISSUE TITLE
http://localhost:8088 throws ERR_CONNECTION_REFUSED in Chrome, MAC OS

### ISSUE THREAD

**Issue by veed76** [aschmelyun/docker-compose-laravel#87]
Hi @aschmelyun 
Thanks for this demo, I created the demo by referring to your video tutorial.

I'm using MAC OS and this is the screenshot of my terminal
<img width="1067" alt="Screenshot 2020-12-04 at 11 31 30 AM" src="https://user-images.githubusercontent.com/20658698/101127779-43412f00-3624-11eb-8e25-2ea6a93b5900.png">

In the browser, I hit  this URL: http://localhost:8088 and get ERR_CONNECTION_REFUSED  in Chrome
<img width="928" alt="Screenshot 2020-12-04 at 11 33 06 AM" src="https://user-images.githubusercontent.com/20658698/101127875-7daacc00-3624-11eb-99f0-9886a3a0859d.png">

Can you please help me? where I'm wrong?

Thank you.

**Comment by roshan-perera** [comment]
As per the docker-compse.yml , url should be 

http://localhost:8080

**Comment by aschmelyun** [comment]
@roshan-perera is correct, although with a recent version I just pushed out, that port has been updated to :80, so you can just use http://localhost
