### ISSUE TITLE
Dockerfile for production

### ISSUE THREAD

**Issue by atreya2011** [aschmelyun/docker-compose-laravel#88]
First of all, thank you for all the hard work in setting up this repo with Dockerfile(s) for creating a dev environment for Laravel. It would be great if there are Dockerfile(s) for use in a production environment as well 🙇🏼‍♂️

**Comment by aschmelyun** [comment]
With the latest updates to this setup, you should be able to use it confidently in production with Docker Compose! If you want a single, standalone Docker image to run a Laravel application, I'd recommend taking a look at ServerSideUp's images here: https://github.com/serversideup/docker-php
