### ISSUE TITLE
What's the point of the npm entrypoint?

### ISSUE THREAD

**Issue by fbnlsr** [aschmelyun/docker-compose-laravel#9]
Why is the npm container has an `entrypoint` of `npm` set?

If I understand correctly, the default behaviour of `docker-compose run` is to use the service's name as entrypoint? Why put it for this container then?

**Comment by aschmelyun** [comment]
Hey @fbnlsr 

The reason I've kept this in is that in the [video](https://www.youtube.com/watch?v=I980aPL-NRM) I made showing the composer/artisan/npm services, you can add additional flags to it (e.g. `entrypoint: ['npm', '--no-bin-links']`). I just decided to keep it in the repo as a reminder of that. You're right though, it shouldn't be necessary!
