### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by aqieez** [aschmelyun/docker-compose-laravel#90]
I have cloned the repo. in src, I have cloned my own Laravel project. after building when I go to localhost I am getting 403 forbidden error. How can I resolve this?

steps I took:
1)docker-compose up -d --build site
2)cloned project into src
3) docker-compose run --rm composer install
4)docker-compose build && docker-compose up -d

after when I go to localhost:80 it shows me 403 forbidden. what is wrong with this? please help

**Comment by Albertopeinado96** [comment]
```
docker-compose run --rm npm install
docker-compose run --rm npm run dev
```

Also check you have the .env file in the laravel folder.
