### ISSUE TITLE
For performance reasons for WSL2, we should put the /src folder in the linux file system.

### ISSUE THREAD

**Issue by tkoop** [aschmelyun/docker-compose-laravel#92]
When using WSL 2, Microsoft recommends you "store your files in the WSL file system".  Maybe instead of having the /src volume in the Windows filesystem, it should be in the Linux file system.  As it is, I've gotten this docker compose setup to work, but a page load takes a long time.

https://docs.microsoft.com/en-us/windows/wsl/compare-versions

**Comment by Raj-Joshi-dev** [comment]
Hi, @tkoop Could you please elaborate on this? I am facing slow page loads too. Also, mysql container always exits with code 1.

![image](https://user-images.githubusercontent.com/52413491/109871408-7454ee00-7c6b-11eb-9c93-b1eebf46e440.png)

**Comment by tkoop** [comment]
In docker-compose.yml, I set the volume(s) to be this: ~/src:/var/www/html:delegated
The second part (after the ":") refers to the location in the docker container.  The first part (before the ":"), refers to the location in WSL.  Neither of these point to the Windows file system.  The way I got the page loads to be fast is to do this:  In Windows command prompt, "cd" to your git project/docker-compose directory. Then run the "wsl" command there.  This will bring up the Linux terminal with you in the correct directory.  Then run the "docker-compose up -d site" command from there, from wsl (not from in Windows).  Then if you "cd ~/src", you can navigate to your src directory in your Linux's home folder.  This is where your website will live. If you're using VS Code, you can type "code ." there and bring up VS Code in Windows.

I'm sorry, I can't help you with mysql.  But try setting the volume to be something like this: `~/mysql:/var/lib/mysql`  And delete that directory first, so docker can create it.

I've stopped using Windows.  I use Linux Mint now, and everything just works better.

**Comment by Raj-Joshi-dev** [comment]
Hey thanks for your reply, I have switched back to Linux (Ubuntu 20.04) as well. Things just work so well natively. Now I use the same dev environment without any problems as well. :smile:

**Comment by aschmelyun** [comment]
Closing this out, but @tkoop is 100% correct. If you're using WSL2 on Windows, it's highly recommended to put your application and mounted volume on the Linux filesystem. When using the WSL2 terminal, you can find where that filesystem resides at by going to the home directory,  `cd ~`, and keeping your project anywhere in there. 

If you do this, you should notice a decent response time from your local app's dev environment!
