### ISSUE TITLE
Composer wont work

### ISSUE THREAD

**Issue by ExXxO** [aschmelyun/docker-compose-laravel#93]
If i run **docker-compose run --rm composer create-project laravel/laravel .** as mentioned in README

Docker ends with this error
```
Creating a "laravel/laravel" project at "./"
Installing laravel/laravel (v8.5.9)
    Failed to download laravel/laravel from dist: /var/www/html/vendor/composer does not exist and could not be created.
    Now trying to download from source
  - Syncing laravel/laravel (v8.5.9) into cache
  - Installing laravel/laravel (v8.5.9): Cloning a96fe93207 from cache
    Install of laravel/laravel failed


  [RuntimeException]
  Could not delete /var/www/html/.:


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package>] [<directory>] [<version>]

ERROR: 1

```

**Comment by shaqaruden** [comment]
I'm having a similar issue with `docker-compose run --rm composer install`

**Comment by shaqaruden** [comment]
@aschmelyun any assistance with this issue?

**Comment by shaqaruden** [comment]
@ExXxO I figured something out. Try adding the -u option to the run command

`docker-compose run --rm -u laravel composer create-project laravel/laravel .`

applying this to my issue I was able to get `composer install` to run

**Comment by Jobinjose01** [comment]
I have the same issue
`docker-compose run --rm composer install
Creating gazit_composer_run ... done
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package mtdowling/cron-expression is abandoned, you should avoid using it. Use dragonmantank/cron-expression instead.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Class Faker\Provider\uk_Ua\Payment located in ./vendor/fzaninotto/faker/src/Faker/Provider/uk_UA/Payment.php does not comply with psr-4 autoloading standard. Skipping.
Class Egulias\EmailValidator\Exception\ExpectedQPair located in ./vendor/egulias/email-validator/EmailValidator/Exception/ExpectingQPair.php does not comply with psr-4 autoloading standard. Skipping.
Class App\Http\Controllers\CallController located in ./app/Http/Controllers/CallController_old.php does not comply with psr-4 autoloading standard. Skipping.
Class App\Http\Controllers\Pages\AdminPagesController located in ./app/Http/Controllers/Pages/AdminPagesController_old.php does not comply with psr-4 autoloading standard. Skipping.
Class App\Branch located in ./app/Branch_old.php does not comply with psr-4 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

Deprecated: Method ReflectionParameter::getClass() is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 811

Deprecated: Method ReflectionParameter::getClass() is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 885

Deprecated: Method ReflectionParameter::getClass() is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 811

Deprecated: Method ReflectionParameter::getClass() is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 885
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 255
ERROR: 255
`
Any suggestion I tried @shaqaruden solution it didn't worked

**Comment by aschmelyun** [comment]
@ExXxO It looks like your problem _may_ have stemmed from an outdated version of Composer, or a problem with the permissions and user options in the container. 

Is this still an issue? Have you tried adding the `-u laravel` option that @shaqaruden added above? 

Leaving this open for now in case someone else has the same issue, please let me know!

**Comment by aschmelyun** [comment]
@Jobinjose01 Your issue seems to be related to your actual application dependencies, not the actual Composer container.

**Comment by chrisloftus** [comment]
@aschmelyun @Jobinjose01 This is because the composer image runs php8:alpine and I'm guessing your PHP files are using deprecated functions in PHP 8. Will post here when I have a solution.

**Comment by chrisloftus** [comment]
@aschmelyun @Jobinjose01 Can use this composer image instead https://hub.docker.com/r/herloct/composer/

Change `composer.dockerfile` to `FROM herloct/composer:1.4.2-php5.6`

Then run `docker-compose down && docker-compose up -d --buiild` 👍

**Comment by Jobinjose01** [comment]
@aschmelyun Yes the actula issue was dependency on other extensions , that are not installed on the container, by adding following dependancies it worked.

`# Install dependencies
RUN apk update && apk add --no-cache \
    bash \
    build-base shadow vim curl \
    php7 \
    php7-fpm \
    php7-common \
    php7-pdo \
    php7-pdo_mysql \
    php7-mysqli \
    php7-mcrypt \
    php7-mbstring \
    php7-xml \
    php7-openssl \
    php7-json \
    php7-phar \
    php7-zip \
    php7-gd \
    php7-dom \
    php7-session \
    php7-zlib \
    zip libzip-dev
    
RUN docker-php-ext-install pdo_mysql

RUN docker-php-ext-install zip exif`

Also I can directly install the composer inside alpine container right ? 
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer in the php.dockerfile

@chrisloftus Thanks for your reply.
